YYHELP: yyhelp: add yyhelp-0.9
Signed-off-by: Tim Janik <timj@gnu.org>

diff --git a/yyhelp/yyhelp b/yyhelp/yyhelp
--- a/yyhelp/yyhelp
+++ b/yyhelp/yyhelp
@@ -19,7 +19,7 @@
 #set -e	# exit on errors
 #set -x	# show commands
 
-VERSION=YummyYummySourceControl-0.8b
+VERSION=YummyYummySourceControl-0.9
 
 # setup
 SETBOLD=true ; SETNORM=true ; COLOR= ; OUT=cat ; YYHELP=
@@ -70,12 +70,14 @@ test -z "$GITURL" && GITURL="`cd \"$gitdir\" && pwd`" # no url, must be local
 function list_committable() { # [FILES...]
     test -s "$gitdir/commit-ignore" && commitignore="$gitdir/commit-ignore" || commitignore=
     test -z "$*" && commitdir=. || commitdir=
+    stripprefix="$gitprefix"
+    test -n "$stripprefix" -a "${stripprefix: -1}" != / && stripprefix="$stripprefix/" # force trailing /
     git-diff-index --name-status --no-renames HEAD -- $commitdir "$@" | while IFS="$TAB" read -r mode file ; do
 	case "$mode" in
 	    D)	test -n "$(git-diff-files -- "$file")" && mode=! ;;
 	    M)	test -n "$commitignore" && fgrep -qx "$file" "$commitignore" && mode=n ;;
 	esac
-	echo "$mode  ${file#$gitprefix}"
+	echo "$mode  ${file#$stripprefix}"
     done
 }
 
@@ -114,16 +116,16 @@ case "/$0" in
 		git-var GIT_AUTHOR_IDENT    2>/dev/null | grep -q '\b[0-9]\{8,\}[ ]\+[+-][0-9]\+ *$' || exit_err 9 "$0: missing commit author information"
 		git-var GIT_COMMITTER_IDENT 2>/dev/null | grep -q '\b[0-9]\{8,\}[ ]\+[+-][0-9]\+ *$' || exit_err 9 "$0: missing committer information"
 		AIDENT=$(git-var GIT_AUTHOR_IDENT    | sed 's/\b\([0-9]\{8,\}[ ]\+[+-][0-9]\+ *\)$/\n\1/' | {
-		  read author; read time; echo -n "  $author" ; echo $time | awk '{ print strftime (" %F %T %z", $1) }'
+		  read author; read time; echo -n "  $author" ; echo $time | gawk '{ print strftime (" %F %T %z", $1) }'
 		})
 		CIDENT=$(git-var GIT_COMMITTER_IDENT | sed 's/\b\([0-9]\{8,\}[ ]\+[+-][0-9]\+ *\)$/\n\1/' | {
-		  read author; read time; echo -n "  $author" ; echo $time | awk '{ print strftime (" %F %T %z", $1) }'
+		  read author; read time; echo -n "  $author" ; echo $time | gawk '{ print strftime (" %F %T %z", $1) }'
 		})
 		# construct commit message
 		echo > "$GIT_DIR/commit-editmsg.txt" || exit $? # abort if not writable
 		cat >> "$GIT_DIR/commit-editmsg.txt" <<-_EOF_HERE
 		#YY: ----------------------------------------------------------------------
-		#YY: Files to be committed (determined by "#YY:F"):
+		#YY: Files to be committed (detected by "#YY:F"):
 		#YY:
 _EOF_HERE
 		list_committable "$@" | sed 's/^/#YY:F   /' >> "$GIT_DIR/commit-editmsg.txt"
@@ -149,18 +151,35 @@ _EOF_HERE
 		$verify_msg && test -x "$GIT_DIR/hooks/commit-msg" && { "$GIT_DIR/hooks/commit-msg" "$GIT_DIR/commit-msg.txt" || exit $? ; }
 		mlines=`git-stripspace < "$GIT_DIR/commit-msg.txt" | wc -l`
 		test 0 -lt "$mlines" || exit_err 3 "** Aborting commit, missing commit message..."
-		# prepare commit file list
-	        CFILES=`mktemp -t yyFILES.$$XXXXXX` && touch $CFILES || exit_err 9 "$0: failed to create temporary file"
-		trap "rm -f $CFILES" 0 HUP INT QUIT TRAP USR1 PIPE TERM
+		# save current index around commit (since GIT_INDEX_FILE=tmpindex git-commit is buggy)
+		TMPINDEX=`mktemp "$GIT_DIR/.precommittindex$$.XXXXXX"` && cp -p "$GIT_DIR/index" "$TMPINDEX" || exit_err 9 "$0: failed to create temporary file"
+		trap 'mv -f "$TMPINDEX" "$GIT_DIR/index"' 0 HUP INT QUIT TRAP USR1 PIPE TERM
+		# unstage everything in index
+		git-read-tree HEAD
+		# stage files from commit message
 		grep "^#YY:F " "$GIT_DIR/commit-editmsg.txt" |                  # filter #YY:F
-		  sed -e "s/^#YY:F \+[^ ]\+ \+//" |                             # extract file names
-		  sed -e 's,["$\\],\\&,g' -e 's/\(.*\)/"\1"/' > "$CFILES"       # enquote file names
+		  sed -e "s/^#YY:F \+//" | {                                    # extract file names
+                    while IFS=" " read -r mode file ; do
+		      case "$mode" in
+		      D)  	git-update-index --force-remove -- "$file" || exit_err 5 "** Aborting commit, removing failed: $file" ;;
+		      A|M)	git-update-index --add          -- "$file" || exit_err 6 "** Aborting commit, adding failed: $file" ;;
+		      n)        ;; # commitignore
+		      '!')      ;; # missing file
+		      *)        exit_err 7 "** Aborting commit, unknown file mode: $mode $file" ;;
+		      esac
+		    done
+		  }
 		rm -f "$GIT_DIR/commit-editmsg.txt"
-		eval "commitfiles=($(cat "$CFILES" ))"                          # fill array with quoted file names
-		test -n "${commitfiles[*]}" || exit_err 0 "** Nothing to commit."
-		git-ls-files --error-unmatch -- "${commitfiles[@]}" || exit $?  # check commit file list
-		git-commit -F "$GIT_DIR/commit-msg.txt" -- "${commitfiles[@]}" ; ccode=$?
+		# abort for empty committs
+		git-diff-index --cached HEAD | grep -q '.' || exit_err 0 "** Nothing to commit."
+		# actually commit changes
+		git-commit -F "$GIT_DIR/commit-msg.txt" ; ccode=$?
+		# cleanup, restore old index and force update on comitted files
 		test 0 = $ccode && rm -f "$GIT_DIR/commit-msg.txt" "$GIT_DIR/commit-editmsg.txt"
+		mv -f "$TMPINDEX" "$GIT_DIR/index"
+		trap - 0 HUP INT QUIT TRAP USR1 PIPE TERM
+		git-update-index --refresh --again > /dev/null  # update stat info
+		# handle auto pushing
 		test 0 = $ccode -a "true" = "`git-config --bool yyhelp.auto-push-commits`" && yypushpull
 		exit $ccode ;;
 */yydiff)	args=`getopt -n "$0" -o r: -- "$@"`; [ $? = 0 ] || exec yyhelp; eval set -- "$args"
@@ -203,7 +222,7 @@ _EOF_HERE
 		test -n "$OC"		&& echo "Origin:   $OC"
 		;;
 */yylsbranches)	test -n "$*" && exec yyhelp
-		exec git-branch $COLOR ;;
+		exec git-branch $COLOR -a ;;
 */yylstags)	test -n "$*" && exec yyhelp
 		exec git-tag -l '.*' ;;
 */yypull)	test -n "$*" && exec yyhelp
@@ -254,6 +273,8 @@ test "x$1" = "x--install-aliases" && {
 					   { echo "$0: failed to install: missing git >= 1.5.0" >&2 ; exit 2 ; }
 	test -x ./yyhelp		|| { echo "$0: failed to install: missing ./yyhelp" >&2 ; exit 2 ; }
 	test -x /bin/bash		|| { echo "$0: failed to install: missing /bin/bash" >&2 ; exit 2 ; }
+	gawk --version 2>/dev/null | fgrep -q "GNU Awk" ||
+	                                   { echo "$0: failed to install: missing GNU awk (/usr/bin/gawk)" >&2 ; exit 2 ; }
 	set -e
 	for i in $YYHELP_ALIASES ; do
 		test -L $i || ln -vs yyhelp $i
