jj-fzf/jj-fzf: check basic deps, jj, fzf, GNU sed
Signed-off-by: Tim Janik <timj@gnu.org>

diff --git a/jj-fzf/jj-fzf b/jj-fzf/jj-fzf
--- a/jj-fzf/jj-fzf
+++ b/jj-fzf/jj-fzf
@@ -5,7 +5,7 @@ SCRIPTNAME=`basename $0` && function die  { [ -n "$*" ] && echo "$SCRIPTNAME: **
 SELF="$0"
 
 # == PREVIEW fast path ==
-export REVPAT='^[^a-z()0-9]*([k-xyz]{7,})([?]*)\ '		# lines start, ignore --graph, parse revision letters, catch '??'-postfix
+export REVPAT='^[^a-z()0-9]*([k-xyz]{7,})([?]*)\ '		# line start, ignore --graph, parse revision letters, catch '??'-postfix
 if test -n "${JJFZF_OUTER_TEMPD:-}" -a -n "${JJ_CONFIG:-}" \
 	-a "${1:-}" == preview					# preview command, nested invocation
 then
@@ -33,6 +33,11 @@ then
   fi
   exit 0
 fi
+
+# == Check Deps ==
+jj --version | grep -Eq 'jj [1-9]\.|jj 0\.2[2-9]\.|jj 0.[3-9][0-9]' || die 'jj-0.22 is required'
+fzf --help | grep -Fq ' --header-first' || die 'fzf-0.29 is required'
+sed --version | grep -Fq 'GNU sed' || die 'GNU sed is required'
 
 # == Config ==
 declare -A DOC
