jj-fzf/jj-fzf: describe: allow user cancellation
Signed-off-by: Tim Janik <timj@gnu.org>

diff --git a/jj-fzf/jj-fzf b/jj-fzf/jj-fzf
--- a/jj-fzf/jj-fzf
+++ b/jj-fzf/jj-fzf
@@ -9,8 +9,17 @@ SELF="$0"
 JJROOT=$(jj root) || die "$PWD: not a JJ repository"
 JJFZFSHOW="jj --no-pager --ignore-working-copy show --tool true"
 JJFZFPAGER="less -Rc"
+TEMPD=
 
 # == Utils ==
+# Create temporary dir, assigns $TEMPD
+temp_dir()
+{
+  test -n "$TEMPD" || {
+    TEMPD="`mktemp --tmpdir -d jjfzf0XXXXXX`" || die "mktemp failed"
+    trap "rm -rf '$TEMPD'" 0 HUP INT QUIT TRAP USR1 PIPE TERM
+  }
+}
 # Match JJ revision as first ASCII word (e.g. as in builtin_log_oneline)
 REVPAT='^[^a-z()0-9]*([k-xyz]{7,})\ '
 # Extract JJ revision from first word
@@ -28,6 +37,8 @@ rev_changeid()	( $JJFZFSHOW -T 'change_id' -r "$1" )
 rev_commitid()	( $JJFZFSHOW -T 'commit_id' -r "$1" )
 # List all branches of a revision
 rev_branches()	( $JJFZFSHOW -T 'concat(separate(" ",branches))' -r "$1" )
+# Get revision description
+rev_description() ( $JJFZFSHOW -T 'concat(description)' -r "$1" )
 # Condense commit empty/description/parent state into a key word
 rev_edpstate()
 (
@@ -63,16 +74,46 @@ echo_signoff()
       sed -e 's/>.*/>/ ; s/^/Signed-off-by: /'
   fi
 )
+# Echo current or default message
 echo_commit_msg()
 (
   R="$1"
+  S=$(rev_edpstate "$R")
+  # keep existing message
+  [[ $S =~ -silent- ]] || {
+    rev_description "$R"
+    return
+  }
+  # start with file name prefixes
+  cd "$JJROOT" # create root relative file names
   FILES=()
   readarray -t FILES < <(jj log --no-graph -r "$R" -T '' -s | sed 's/^\w //')
   test ${#FILES[@]} -gt 0 &&
     printf "%s: \n" "${FILES[@]}" ||
       echo Empty...
+  # ensure signoff
   echo_signoff
 )
+# Run user editor: user_editor_on_var <FILE> <VARIABLE>
+user_editor_on_var()
+{
+  local FILE="$1" N=
+  declare -n _ueovMSG="$2"			# <VARIABLE> alias
+  # create msg file
+  temp_dir
+  local TEMPFILE="$TEMPD/$FILE"
+  cat >"$TEMPFILE" <<<"$_ueovMSG"
+  # edit commit msg
+  $EDITOR "$TEMPFILE" &&
+    N="$(cat "$TEMPFILE")" && {
+      test "$_ueovMSG" != "$N" &&
+	_ueovMSG="$(cat "$TEMPFILE")"
+      rm -f "$TEMPFILE"
+      return 0
+    }
+  rm -f "$TEMPFILE"
+  return 1
+}
 
 # == Functions ==
 FUNCTIONS=()
@@ -168,13 +209,14 @@ KEYBINDINGS["Alt-C"]="commit"
 describe()
 (
   R="$(xrev "${1:-@}")"
-  test silent == "$($JJFZFSHOW -r "$R"  -T 'separate(" ",if(!description, "silent"))')" && {
-    M="$(echo_commit_msg "$R")"
-    test z "$M" ||
-      jj describe -r "$R" -m "$M"
+  O="$(rev_description "$R")"
+  MSG="$(echo_commit_msg "$R")"
+  user_editor_on_var "COMMIT.txt" MSG ||
+    ERROR "Describe cancelled by user"
+  test "$O" == "$MSG" || {
+    jj describe --no-edit -r "$R" -m "$MSG" ||
+      sleep 1
   }
-  jj describe -r "$R" ||
-    sleep 1
 )
 KEYBINDINGS["Ctrl-E"]="describe"
 
