jj-fzf/jj-fzf: Alt-K: make the backout commit the working-copy
Signed-off-by: Tim Janik <timj@gnu.org>

diff --git a/jj-fzf/jj-fzf b/jj-fzf/jj-fzf
--- a/jj-fzf/jj-fzf
+++ b/jj-fzf/jj-fzf
@@ -1,7 +1,7 @@
 #!/bin/bash
 # This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
 set -Eeuo pipefail #-x
-SCRIPTNAME=`basename $0` && function die  { [ -n "$*" ] && echo "$SCRIPTNAME: **ERROR**: $*" >&2; exit 127 ; }
+SCRIPTNAME=`basename $0` && function die  { [ -n "$*" ] && echo "$SCRIPTNAME: **ERROR**: $*" >&2; sleep 1; exit 127 ; }
 SELF="$0"
 
 # == PREVIEW fast path ==
@@ -175,12 +175,38 @@ xrev_or_commit()
 rev_bookmarks()	( $JJFZFSHOW -T 'concat(separate(" ",bookmarks))' -r "$1" )
 # Get revision description
 rev_description() ( $JJFZFSHOW -T 'concat(description)' -r "$1" )
+
 # Condense commit empty/description/parent state into a key word
 rev_edpstate()
 (
   export EDPSTATE='separate("-", if(empty, "empty", "diff"), if(description, "description", "silent"), "p" ++ self.parents().len()) ++ "\n"'
   $JJFZFSHOW -r "$1" -T "$EDPSTATE" # empty-description-p2 diff-silent-p1 etc
 )
+
+# List children of a revision
+rev_children()
+(
+  jj --no-pager --ignore-working-copy log --no-graph -r "all: $1+" -T 'change_id++"\n"'
+)
+
+# diff_arrays A B C - store the elements from A without elements from B in C
+diff_arrays()
+{
+  local -n array_A_=$1
+  local -n array_B_=$2
+  local -n array_C_=$3
+  declare -A counts_
+  # Mark elements in A
+  for elem in "${array_A_[@]}" ; do
+    counts_["$elem"]=1
+  done
+  # Add all of B to C if not in A
+  for elem in "${array_B_[@]}"; do
+    test -z "${counts_[$elem]:-}" &&
+      array_C_+=("$elem")
+  done
+}
+
 # Require .git directory and set GIT_DIR
 require_git_dir()
 {
@@ -571,16 +597,23 @@ split-interactive()
 KEYBINDINGS["Alt-I"]="split-interactive"
 
 # Backout Commit
-DOC['backout']='Use `jj backout` to create a new (disconnected) commit that reverts the currently selected revision.'
+DOC['backout']='Use `jj backout` to create a new commit on top of the currently selected revision that undoes the changes in its parent and becomes the new working-copy.'
 backout()
 (
   R="$(xrev "${1:-@}")"
+  A=( $(rev_children "$R") )
   ( set -x
-    jj backout -r "$R" -d "$R") ||
-    sleep 1
-  # TODO: move @ to $R
+    jj backout -r "$R" -d "$R"
+  ) || sleep 1
+  B=( $(rev_children "$R") )
+  C=() && diff_arrays A B C
+  [ ${#C[@]} -eq 1 ] ||
+    die "failed to find newly created backout revision"
+  ( set -x
+    jj edit -r "${C[0]}"
+  ) || sleep 1
 )
-KEYBINDINGS["Alt-K"]="backout"
+KEYBINDINGS["Alt-K"]="backout"		FIRSTS="$FIRSTS backout"
 
 # Line History
 DOC['line-history']='WIP: View history of each line.'
